# Generated by Django 3.2.9 on 2021-11-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpanInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_start_timestamp', models.CharField(max_length=64)),
                ('trace_id', models.CharField(max_length=64)),
                ('span_id', models.CharField(max_length=64)),
                ('parent_span_id', models.CharField(max_length=64)),
                ('span_start_timestamp', models.CharField(max_length=64)),
                ('duration', models.CharField(max_length=64)),
                ('operation_name', models.CharField(max_length=150)),
                ('service_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TraceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(max_length=64)),
                ('label', models.IntegerField(default=0, max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
