# Generated by Django 3.2.9 on 2021-11-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211121_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceinformation',
            name='label',
            field=models.IntegerField(default=0),
        ),
    ]
