# Generated by Django 3.2.8 on 2022-01-30 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_traceinformation_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spaninformation',
            name='trace_id',
        ),
        migrations.RemoveField(
            model_name='spaninformation',
            name='trace_start_timestamp',
        ),
        migrations.AddField(
            model_name='spaninformation',
            name='error_message',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='spaninformation',
            name='trace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.traceinformation'),
        ),
        migrations.AddField(
            model_name='traceinformation',
            name='trace_start_timestamp',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traceinformation',
            name='label',
            field=models.BooleanField(default=False),
        ),
    ]
