# Generated by Django 3.2.8 on 2022-01-31 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20220131_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceinformation',
            name='trace_id',
            field=models.CharField(max_length=64),
        ),
    ]
