# Generated by Django 3.2.8 on 2022-01-31 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_traceinformation_trace_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaninformation',
            name='parent_span_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='spaninformation',
            name='span_id',
            field=models.CharField(max_length=64),
        ),
    ]
