# Generated by Django 3.2.8 on 2022-01-31 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20220131_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spaninformation',
            old_name='parent_span_id',
            new_name='parent_span_uuid',
        ),
        migrations.RenameField(
            model_name='spaninformation',
            old_name='span_id',
            new_name='span_uuid',
        ),
        migrations.RenameField(
            model_name='traceinformation',
            old_name='trace_id',
            new_name='trace_uuid',
        ),
    ]
